name: CD

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_type }}
  cancel-in-progress: false

permissions:
  contents: write
  packages: write

jobs:
  npm:
    runs-on: ubuntu-latest
    env:
      EMSDK_VERSION: 4.0.5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
      - run: |
          git clone --depth 1 https://github.com/emscripten-core/emsdk.git
          ./emsdk/emsdk install ${{ env.EMSDK_VERSION }}
          ./emsdk/emsdk activate ${{ env.EMSDK_VERSION }}
          rm -rf emsdk/upstream/emscripten/cmake
          echo "$(pwd)/emsdk/upstream/emscripten" >> $GITHUB_PATH
      - run: make -C bindings/webassembly compile
      - run: make -C bindings/webassembly test
      - run: cd bindings/webassembly && npm version ${{ github.ref_name }} && npm publish
        if: github.ref_type == 'tag'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  python:
    strategy:
      matrix:
        platform:
          - os: ubuntu-latest
            version: 3.11
          - os: ubuntu-latest
            version: 3.12
          - os: macos-15
            version: 3.11
          - os: macos-15
            version: 3.12

    runs-on: ${{ matrix.platform.os }}
    env:
      CC: clang
      CXX: clang++
    steps:
      - uses: snok/install-poetry@v1.3.4
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.platform.version }}

      - name: Set package version
        if: github.ref_type == 'tag'
        run: |
          VERSION="${{ github.ref_name }}"
          VERSION="${VERSION#v}"
          poetry version "$VERSION"

      - run: make -C bindings/python compile
      - run: make -C bindings/python test
      - uses: actions/upload-artifact@v4
        with:
          name: python-bindings-${{ matrix.platform.os }}-${{ matrix.platform.version }}
          path: bindings/python/dist/*

  python-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6

      - uses: actions/checkout@v4
      - name: Set package version
        if: github.ref_type == 'tag'
        run: |
          VERSION="${{ github.ref_name }}"
          VERSION="${VERSION#v}"
          uv version --no-sync "$VERSION"

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - run: docker build --tag pycruzer-arm64 . --file bindings/python/Dockerfile --progress plain --platform linux/arm64
      - run: docker build --tag pycruzer-amd64 . --file bindings/python/Dockerfile --progress plain --platform linux/amd64
      - run: docker create --name pycruzer-builder-arm64 pycruzer-arm64
      - run: docker create --name pycruzer-builder-amd64 pycruzer-amd64
      - run: mkdir -p bindings/python/dist/docker
      - run: docker cp pycruzer-builder-arm64:/source/bindings/python/dist bindings/python/dist/docker
      - run: docker cp pycruzer-builder-amd64:/source/bindings/python/dist bindings/python/dist/docker
      - run: mv bindings/python/dist/docker/dist/*.whl bindings/python/dist
      - run: rm -rf bindings/python/dist/docker

      - uses: actions/upload-artifact@v4
        with:
          name: python-bindings-docker
          path: bindings/python/dist/*

  github:
    needs: [ python, python-docker ]
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: bindings/python/dist
          merge-multiple: true
      - run: tree bindings/python/dist
      - run: gh config set prompt disabled
        env:
          GH_TOKEN: ${{ github.token }}
      - run: |
          gh release create ${{ github.ref_name }} --draft=false --title ${{ github.ref_name }} --target "$GITHUB_SHA" --generate-notes
          gh release upload --clobber ${{ github.ref_name }} bindings/python/dist/*
        if: github.ref_type == 'tag'
        env:
          GH_TOKEN: ${{ github.token }}
