name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: ubuntu-latest
            cc: clang
            cxx: clang++
          - os: ubuntu-latest
            cc: gcc
            cxx: g++

    runs-on: ${{ matrix.platform.os }}
    env:
      CC: ${{ matrix.platform.cc }}
      CXX: ${{ matrix.platform.cxx }}
    steps:
      - name: Install ClangFormat
        run: pipx install clang-format==19.1.0
      - run: cmake --version
      - uses: actions/checkout@v4
      - run: >
          cmake -S . -B ./build
          -DCMAKE_BUILD_TYPE:STRING=Release
          -DCRUZER_TESTS:BOOL=ON
          -DCRUZER_PYTHON:BOOL=OFF
          -DBUILD_SHARED_LIBS:BOOL=OFF
          -DCMAKE_COMPILE_WARNING_AS_ERROR:BOOL=ON
      - run: cmake --build ./build --config Release --target clang_format_test
      - run: cmake --build ./build --config Release --parallel 4
      - run: cd ./build && ctest --build-config Release --output-on-failure --parallel

  bindings:
    strategy:
      fail-fast: false
      matrix:
        binding:
          - name: webassembly
            os: ubuntu-latest
            cc: gcc
            cxx: g++
          - name: python
            os: ubuntu-latest
            cc: clang
            cxx: clang++
    env:
      EMSDK_VERSION: 4.0.5
      CC: ${{ matrix.binding.cc }}
      CXX: ${{ matrix.binding.cxx }}

    runs-on: ${{ matrix.binding.os }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          git clone --depth 1 https://github.com/emscripten-core/emsdk.git
          ./emsdk/emsdk install ${{ env.EMSDK_VERSION }}
          ./emsdk/emsdk activate ${{ env.EMSDK_VERSION }}
          rm -rf emsdk/upstream/emscripten/cmake
          echo "$(pwd)/emsdk/upstream/emscripten" >> $GITHUB_PATH
        if: matrix.binding.name == 'webassembly'
      - uses: snok/install-poetry@v1.3.4
        if: matrix.binding.name == 'python'
      - run: make -C bindings/${{ matrix.binding.name }} compile
      - run: make -C bindings/${{ matrix.binding.name }} test
