name: test-wheels

on:
  push:

permissions:
  contents: write

jobs:

  python:
    strategy:
      matrix:
        platform:
          - os: macos-15
            version: 3.11
          - os: macos-15
            version: 3.12

    runs-on: ${{ matrix.platform.os }}
    env:
      CC: clang
      CXX: clang++
    steps:
      - uses: snok/install-poetry@v1.3.4
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.platform.version }}

      - run: make -C bindings/python compile
      - run: make -C bindings/python test
      - uses: actions/upload-artifact@v4
        with:
          name: python-bindings-${{ matrix.platform.os }}-${{ matrix.platform.version }}
          path: bindings/python/dist/*
      - run: poetry run pip install bindings/python/dist/pycruzer-*.whl
      - run: poetry run python -c "import pycruzer; print(dir(pycruzer))"
