name: test-wheels

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_type }}
  cancel-in-progress: false

permissions:
  contents: write
  packages: write

jobs:
  python:
#    strategy:
#      matrix:
#        platform:
#          - os: ubuntu-24.04
#            version: 3.11
#          - os: ubuntu-24.04
#            version: 3.12
#
#    runs-on: ${{ matrix.platform.os }}
    runs-on: ubuntu-latest
    env:
      CC: clang
      CXX: clang++
    steps:
      - uses: actions/checkout@v4

#      - uses: actions/setup-python@v5
#        with:
#          python-version: ${{ matrix.platform.version }}
#
#      - run: make -C bindings/python compile

#      - name: Install Poetry
#        uses: snok/install-poetry@v1.3.4
#
#      - name: Build a binary wheel and a source tarball
#        run: poetry build
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.3

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Test installing wheel
        run: pip install dist/pycruzer-0.1.0-cp312-cp312-linux_x86_64.whl

      - name: Test module
        run: python -c "import pycruzer; print(dir(pycruzer))"

      - uses: actions/upload-artifact@v4
        with:
          name: python-bindings
          path: dist/*
